//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dish
    {
        public Dish()
        {
            this.OrderDish = new HashSet<OrderDish>();
        }
    
        public int DishId { get; set; }
        public string DishName { get; set; }
        public decimal Price { get; set; }
        public bool Available { get; set; }
    
        public virtual ICollection<OrderDish> OrderDish { get; set; }
    }
}
